# Generated by Django 3.0.5 on 2020-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('TodoTitle', models.CharField(max_length=100)),
                ('TodoDesc', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('DueDate', models.DateField()),
            ],
        ),
    ]
